#!/usr/bin/env python
__author__ = 'Jared Stroud', "Andrew Garbutt"

import umadbroRequests, sys
madRequest = umadbroRequests.Request()


if len(sys.argv) != 2: # If there's no argument throw an error.
    print("Usage: umadbro tool_name")
    sys.exit()
else:
    usr_args = sys.argv[1]
    madRequest.make_request(usr_args)


